### ISSUE TITLE
Testing: "Map by groups" block

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Mapping#124]
The `map-by-groups-block-plus-optimization` branch introduces the "Map by groups" block for site pages. With this block, users can view groups of items on a map, and click on an individual group to view its component items (or, more accurately, its items' features). For example, we have a map that contains item sets. When clicked, an item set will expand to all items that are assigned to that item set.

The module calculates a group's location on the map by collecting all its component features and generating what's called a [convex hull](https://en.wikipedia.org/wiki/Convex_hull) around the outermost points. Administrators have the option to render a groups as a polygon (i.e. the convex hull) or as a central point of the polygon.

In addition to testing the new "Map by groups" block, you'll need to test the existing "Map by attachment" and "Map by query" blocks, including their timeline and WMS overlay features. This is due to major refactoring of the block code that I needed to do. After checking out the `map-by-groups-block` branch you should see no difference in your existing Mapping blocks: same configuration, same behavior, and same output.

To test this block, add the new "Map by groups" block to a page. You should see the normal "Default view" and "WMS overlays" sections and a new "Groups" section that contains the following fields:

- **Group by**: Select the type of group. These match common ways that users want to group their items.
  - Item sets
  - Resource classes
  - Property values (is exactly)
  - Property values (contains)
  - Property values (is item with ID)
  - Properties (has any value)
- **Feature type**: Select the type of feature to represent each group.
  - Polygon: A bounding volume around the outermost features.
  - Point: The central point of the bounding volume.

Once a user selects a "Group by" the form should expand with fields. The fields that appear depend on what the user selects.

### Item sets

- **Filter by resource class**: Filter the items by the selected resource class (i.e. only include items assigned to the selected resource class).
- **Item sets**: Select the item sets to render as groups on the map.

### Resource classes

- **Filter by item set**: Filter the items by the selected item set (i.e. only include items assigned to the selected item set).
- **Resource classes**: Select the resource classes to render as groups on the map.

### Property values (is exactly)

- **Filter by item set**: (see above)
- **Filter by resource class**: (see above)
- **Property**: Select the property of the values to group.
- **Values**: Enter the (exact match) values to render as groups on the map, separated by new lines.

### Property values (contains)

- **Filter by item set**: (see above)
- **Filter by resource class**: (see above)
- **Property**: (see above)
- **Values**: Enter the (matches any part) values to render as groups on the map, separated by new lines.

### Property values (is item with ID)

- **Filter by item set**: (see above)
- **Filter by resource class**: (see above)
- **Property**: (see above)
- **Values**: Enter the (resource ID) values to render as groups on the map, separated by new lines.

### Properties (has any value)

- **Filter by item set**: (see above)
- **Filter by resource class**: (see above)
- **Properties**: Select the properties (that have values) to render as groups on the map.

After you have configured a "Map by groups" block (you should test every combination), view the public page. You should see a map with groups rendered as polygons or points, depending on how you configured it. Verify that each group represents every item in the group. Click on a group and verify that the popup content makes sense for the group. Click on the "Show all" button and verify that the map reloads, rendering all component features. This map should behave identically to the existing "Map by" blocks. Click on the "Return to groups" button and verify that the map reloads, rendering the original groups.

**Comment by allanaaa** [comment]
1. Clicking on the "View all results" doesn't re-zoom the map to contain them, so that's a bit disorienting. 

2. When you click, the text bars/button appear above and below the map, which means the map moves around on the page. We probably don't want to have a container grow or shrink in height when clicked. Maybe we can overlay the results info on the map in some way - or just reserve empty space for it somewhere. 

I wonder if a "Map by groups" block should have some kind of title or text to indicate what's going on inside. So perhaps if there is always a text box indicating the selection of the "Group by" dropdown ("Items grouped by resource class  / [property name] / etc" which then changes to the selected grouping on click would solve both problems. I like that you have it styled consistenly with a search result indicator, and I'd keep that if we can.

**Comment by allanaaa** [comment]
3. I am unsure how the "Group by property (has any value)" is supposed to work - this is by definition only going to load one group, right? 

4. Setting a block to "Group by property (has any value)" with "Date" and no filters or other settings got me the following error:

>  Error
> Call to a member function displayTitle() on null
> 
> Details:
> 
> Error: Call to a member function displayTitle() on null in /var/www/html/amayer/amayer-s/omeka-s/modules/Mapping/view/common/mapping-popup/property-ex-group.phtml:20
> Stack trace:
> #0 /var/www/html/amayer/amayer-s/omeka-s/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(519): include()
> #1 /var/www/html/amayer/amayer-s/omeka-s/vendor/laminas/laminas-view/src/Helper/Partial.php(63): Laminas\View\Renderer\PhpRenderer->render(NULL, NULL)
> #2 /var/www/html/amayer/amayer-s/omeka-s/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(407): Laminas\View\Helper\Partial->__invoke('common/mapping-...', Array)
> #3 /var/www/html/amayer/amayer-s/omeka-s/modules/Mapping/view/common/block-layout/mapping-block-groups.phtml(14): Laminas\View\Renderer\PhpRenderer->__call('partial', Array)
> #4 /var/www/html/amayer/amayer-s/omeka-s/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(519): include('/var/www/html/a...')
> #5 /var/www/html/amayer/amayer-s/omeka-s/vendor/laminas/laminas-view/src/Helper/Partial.php(63): Laminas\View\Renderer\PhpRenderer->render(NULL, NULL)
> #6 /var/www/html/amayer/amayer-s/omeka-s/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(407): Laminas\View\Helper\Partial->__invoke('common/block-la...', Array)
> #7 /var/www/html/amayer/amayer-s/omeka-s/modules/Mapping/src/Site/BlockLayout/MapGroups.php(112): Laminas\View\Renderer\PhpRenderer->__call('partial', Array)
> #8 /var/www/html/amayer/amayer-s/omeka-s/application/src/View/Helper/BlockLayout.php(158): Mapping\Site\BlockLayout\MapGroups->render(Object(Laminas\View\Renderer\PhpRenderer), Object(Omeka\Api\Representation\SitePageBlockRepresentation))
> #9 /var/www/html/amayer/amayer-s/omeka-s/application/src/View/Helper/PageLayout.php(85): Omeka\View\Helper\BlockLayout->render(Object(Omeka\Api\Representation\SitePageBlockRepresentation))
> #10 /var/www/html/amayer/amayer-s/omeka-s/application/view/omeka/site/page/content.phtml(1): Omeka\View\Helper\PageLayout->render(Object(Omeka\Api\Representation\SitePageRepresentation))
> #11 /var/www/html/amayer/amayer-s/omeka-s/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(519): include('/var/www/html/a...')
> #12 /var/www/html/amayer/amayer-s/omeka-s/vendor/laminas/laminas-view/src/View.php(194): Laminas\View\Renderer\PhpRenderer->render(NULL)
> #13 /var/www/html/amayer/amayer-s/omeka-s/vendor/laminas/laminas-view/src/View.php(222): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
> #14 /var/www/html/amayer/amayer-s/omeka-s/vendor/laminas/laminas-view/src/View.php(187): Laminas\View\View->renderChildren(Object(Laminas\View\Model\ViewModel))
> #15 /var/www/html/amayer/amayer-s/omeka-s/vendor/laminas/laminas-view/src/View.php(222): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
> #16 /var/www/html/amayer/amayer-s/omeka-s/vendor/laminas/laminas-view/src/View.php(187): Laminas\View\View->renderChildren(Object(Laminas\View\Model\ViewModel))
> #17 /var/www/html/amayer/amayer-s/omeka-s/vendor/laminas/laminas-mvc/src/View/Http/DefaultRenderingStrategy.php(98): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
> #18 /var/www/html/amayer/amayer-s/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Laminas\Mvc\MvcEvent))
> #19 /var/www/html/amayer/amayer-s/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(171): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent))
> #20 /var/www/html/amayer/amayer-s/omeka-s/vendor/laminas/laminas-mvc/src/Application.php(360): Laminas\EventManager\EventManager->triggerEvent(Object(Laminas\Mvc\MvcEvent))
> #21 /var/www/html/amayer/amayer-s/omeka-s/vendor/laminas/laminas-mvc/src/Application.php(341): Laminas\Mvc\Application->completeRequest(Object(Laminas\Mvc\MvcEvent))
> #22 /var/www/html/amayer/amayer-s/omeka-s/index.php(21): Laminas\Mvc\Application->run()
> #23 {main}

**Comment by jimsafley** [comment]
> 1. Clicking on the "View all results" doesn't re-zoom the map to contain them, so that's a bit disorienting.

Strange. It should set a map view that contains all the features. Do you see a JS error in the console after clicking "View all results"?

> 2. When you click, the text bars/button appear above and below the map, which means the map moves around on the page. We probably don't want to have a container grow or shrink in height when clicked. Maybe we can overlay the results info on the map in some way - or just reserve empty space for it somewhere.

We can't sacrifice the space in the map itself, but reserving empty space might be a good idea. @kimisgold What are your thoughts?

> 3. I am unsure how the "Group by property (has any value)" is supposed to work - this is by definition only going to load one group, right?

It has as many groups as there are properties you set (that have any value).

> 4. Setting a block to "Group by property (has any value)" with "Date" and no filters or other settings got me the following error:

Glad you caught that. It should be fixed now.

**Comment by kimisgold** [comment]
I do like the idea of reserving space. We could provide options for a horizontal bar across the top or a panel to the right or left.

<img width="1029" alt="Screenshot 2024-11-19 at 3 25 42 PM" src="https://github.com/user-attachments/assets/8b2f3629-0214-458c-8105-a483a25de39f">

<img width="1015" alt="image" src="https://github.com/user-attachments/assets/dbb9adc9-6eb7-4448-89de-f16e1fd5ffd6">

**Comment by jimsafley** [comment]
> I do like the idea of reserving space. We could provide options for a horizontal bar across the top or a panel to the right or left.

I think we should provide only a horizontal bar across the top, at least for now.

**Comment by kimisgold** [comment]
The changes are in. Right now, it's hard to get around that top bar appearing and changing the block height after a group is selected. I'd like to float the idea of an additional input in that same area upon load: a select dropdown where the user can choose from the groups available. This might be especially handy if there are polygon overlays that overlap each other.

**Comment by jimsafley** [comment]
> I'd like to float the idea of an additional input in that same area upon load: a select dropdown where the user can choose from the groups available.

Do you mean above the groups map, above the group items map, or both? At any rate, I see the usefulness of it, but it'll have to wait for a future release.

**Comment by kimisgold** [comment]
Above the groups map. It'll help with overlapping group polygons as well as maintaining a consistent height for the block since I envision it sitting in the same space as the group items controls.

**Comment by allanaaa** [comment]
Sorry, I thought I was waiting for a commit that would reserve space above the map. 

Can we put some filler information in there when no group is selected, perhaps simply reflecting the settings of the Groups map? "Group By: X" at the very least, and then other optional filters if needed? 

I like the idea of text selectors, but _something_ has to go in there for now.

**Comment by allanaaa** [comment]
>         Clicking on the "View all results" doesn't re-zoom the map to contain them, so that's a bit disorienting.
> 
> Strange. It should set a map view that contains all the features. Do you see a JS error in the console after clicking "View all results"?

Nope, no errors. 

You can see the third map here: https://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-fourth-site/page/maps-tests

If you click on any of the group pins, you'll see it zooms in to the maximum level, centering on where the pin is (so, the centre of the group's pins).

I wonder if we can also disable clustering just on these maps - I don't think most people will want to cluster their groups? We don't offer it as a map-by-map setting unfortunately.

**Comment by jimsafley** [comment]
> Can we put some filler information in there when no group is selected, perhaps simply reflecting the settings of the Groups map? "Group By: X" at the very least, and then other optional filters if needed?

@kimisgold What do you think? Should we reserve space above the groups map? I'm not so sure. I've looked into adding a select menu where the user can select individual groups, but that's proving to be difficult. It'll have to wait for a future release.

> If you click on any of the group pins, you'll see it zooms in to the maximum level, centering on where the pin is (so, the centre of the group's pins).

I see it happening on your site but I can't reproduce it. I'll continue to investigate.

> I wonder if we can also disable clustering just on these maps - I don't think most people will want to cluster their groups? We don't offer it as a map-by-map setting unfortunately.

It's probably a good idea to add a setting to the Mapping blocks that disables/enables clustering. It'll have to wait for a future release.

**Comment by kimisgold** [comment]
I'm not sure it's worth the effort of creating a placeholder for the moment. Thinking about the exact string, whether the user would want to have "item set" vs "group" or a whole other heading altogether seems more trouble than it's worth when we already have a plan for a feature to go there. The block height changing is a little awkward, but we know we'll address it in the next release.

**Comment by jimsafley** [comment]
As far as I can tell, the only outstanding issues here are things that can wait for a future release. I could not reproduce the "zoom to maximum level" for groups, but I'm okay making a release anyway. @allanaaa Anything further?

**Comment by allanaaa** [comment]
This still feels pretty rudimentary to me. The combination of the map not re-containing all the pins when a group is selected, plus the map moving around on the page, makes the experience disorienting. If you can find somebody else with a testing site to reproduce those and weigh in, I'd be happier. Mapping is one of our bigger modules and I'm not sure we want to try to release a new version ASAP to fix problems in this version. 

Perhaps as one compromise we can put the appearing text row under the map. It'll still move everything else around on the page, but at least this map won't shift around under users' mouses when they're using it. 

Those are the two main issues I've found. Nothing else needs work that I can see.

**Comment by jimsafley** [comment]
> the map not re-containing all the pins when a group is selected, 

I'll try again to get to the bottom of it.

> Perhaps as one compromise we can put the appearing text row under the map. It'll still move everything else around on the page, but at least this map won't shift around under users' mouses when they're using it.

This is a good compromise until I get around to implementing the group selector. I've pushed the change. Try it out.

**Comment by jimsafley** [comment]
I pushed a change that may fix the "fit to bounds" error. Pull and try it out.

**Comment by allanaaa** [comment]
> This is a good compromise until I get around to implementing the group selector. I've pushed the change. Try it out.

Looks good - the text bar just needs some top margin or padding now. 

<img width="1199" alt="Screenshot 2024-12-12 at 14 09 58" src="https://github.com/user-attachments/assets/f52efa76-2037-40bc-9184-0d2ccd81387c" />

**Comment by allanaaa** [comment]
> I pushed a change that may fix the "fit to bounds" error. Pull and try it out.

This is an improvement. It does flash for a second or so at the full world map before refreshing, but I think that's okay. 

My apologies, but I didn't ever get "Group by resource ID" to work. Entering one value per line doesn't get me anything showing on the map, and I'm not clear on what the groups would be in that case. 

Is it supposed to be ranges of IDs become the groups, like if I enter on each line

1-99
100-500
501-1000

I should get 3 groups? And/or, as we do in other places, a line of values, separated by commas, like

1,2,3,4,5
6,7,8,9,10
11,12,13,14,15

You also have "is item with ID" in the dropdown, which I think should be "is resource with ID".

**Comment by jimsafley** [comment]
> Looks good - the text bar just needs some top margin or padding now.

@kimisgold Would you mind doing this?

> My apologies, but I didn't ever get "Group by resource ID" to work. Entering one value per line doesn't get me anything showing on the map, and I'm not clear on what the groups would be in that case.

An "is resource with ID" group is a group of items (with features) that have at least one "resource" value of the specified property and resource ID. Each line in the "Values" field should be one resource ID that represents one group.

> You also have "is item with ID" in the dropdown, which I think should be "is resource with ID".

Thanks. It should be fixed now.

**Comment by jimsafley** [comment]
@allanaaa Kim pushed the text bar style changes. If it looks good, is there anything else we need to do before closing this issue?

**Comment by allanaaa** [comment]
The style looks a bit off with the linked-resource option, because the group name gets turned into a link in the text bar:

<img width="1213" alt="Screenshot 2024-12-17 at 14 11 19" src="https://github.com/user-attachments/assets/02b86986-65b5-46e8-b47e-3569557d834d" />

Also, with this option the property is a required field, right? I can't make a group of all items that have the chosen resource as a linked value in any property?

**Comment by kimisgold** [comment]
I'm wondering if the linked resource thumbnail is at all helpful at this size. Removing it would certainly help standardize the height.

**Comment by jimsafley** [comment]
> I'm wondering if the linked resource thumbnail is at all helpful at this size. Removing it would certainly help standardize the height.

I'm hesitant to remove the link there because it's the only place on that map view where the user can go to the item that represents the group. But if you don't think a link is important there, I can take it out.

> Also, with this option the property is a required field, right? I can't make a group of all items that have the chosen resource as a linked value in any property?

That's right. I'll think about whether this is feasible to do prior to release.

**Comment by jimsafley** [comment]
I've enabled "[Any property]" queries for the value groups (is exactly, contains, is resource with ID). Pull and try it out.

**Comment by jimsafley** [comment]
I've removed the thumbnail from the link. Pull and try it out.

**Comment by allanaaa** [comment]
That's an improvement for sure. 

Small style issues across the themes, which can mostly be fixed in the module I think:

<img width="1479" alt="Screenshot 2024-12-19 at 15 43 58" src="https://github.com/user-attachments/assets/e1ec3d49-e584-4f1b-aea3-43ca5e063643" />
<img width="1485" alt="Screenshot 2024-12-19 at 15 44 06" src="https://github.com/user-attachments/assets/8cd3daab-51e6-43e4-8b30-deaee044606f" />

Freedom: Map pin display needs a line break between image and title; maybe centre the image. Linked text in bottom bar needs contrast with box background.

Lively has those same two issues as well - bad colour contrast and map pin issue. 

<img width="1279" alt="Screenshot 2024-12-19 at 15 42 34" src="https://github.com/user-attachments/assets/864fffa4-d122-419a-a294-6ffc42412c85" />

Foundation: same map pin issue.

<img width="1229" alt="Screenshot 2024-12-19 at 10 40 55" src="https://github.com/user-attachments/assets/5cbccca6-7a33-4bcf-9503-3f466f50ef86" />

Cozy: same link colour contrast.

<img width="1652" alt="Screenshot 2024-12-19 at 15 41 36" src="https://github.com/user-attachments/assets/bd0c7a2d-888c-447d-bcda-162645845719" />

The Daily has a left-aligned button that could be consistent with the other themes, but it works. And the text above the button is really small.

<img width="919" alt="Screenshot 2024-12-19 at 15 41 51" src="https://github.com/user-attachments/assets/68a0b240-7355-4164-a8c7-005004b17d8f" />

Center Row: I don't like the border and text centering, but it works. Also has the map pin problem.

**Comment by allanaaa** [comment]
Some of the themes have the coloured boxes separating the first part from the second; others use a colon. Lively and Freedom both need a space after the colon (I made the links white for better visibility on this) - or to use the coloured-box system instead of a colon:
<img width="474" alt="Screenshot 2024-12-19 at 15 58 20" src="https://github.com/user-attachments/assets/de93a9ad-ac23-41f3-9272-089492e42541" />


<img width="791" alt="Screenshot 2024-12-19 at 15 57 46" src="https://github.com/user-attachments/assets/d2fd21cb-96e1-45da-b4f8-cbbcbb716bd7" />

The other themes are all good on this one.

**Comment by kimisgold** [comment]
I've provided some default styles for resource links within popups, aiming to have the thumbnail occupy its own line with the resource title underneath. They're ready for review.

The group filters are relying on the themes' search filter styles. This is not something I want to overreach with from within Mapping. I would file individual issues with those themes, since the problems you're seeing in Mapping are likely also problems within the default item search filters.

**Comment by allanaaa** [comment]
I like them, but the map doesn't re-centre to contain the pin:
<img width="642" alt="Screenshot 2025-01-07 at 09 17 50" src="https://github.com/user-attachments/assets/2778fc37-bf38-409b-9f77-ba3227b00fab" />

<img width="794" alt="Screenshot 2025-01-07 at 09 17 27" src="https://github.com/user-attachments/assets/20f13270-d1b5-4c50-a9ea-ee78501bb561" />

Whereas it does for other maps on that page: http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-omeka-s-site/page/maps-test

Something about the polygons I presume.

**Comment by jimsafley** [comment]
> but the map doesn't re-centre to contain the pin:

Would you elaborate on this? I'm not seeing the problem, or I'm not understanding it.

**Comment by allanaaa** [comment]
Sorry, "centre" and "pin" weren't the right words. 

If you click on the pin near the top of the third map on this page: http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-omeka-s-site/page/maps-test

It will move the map down so that the entire pop-up is contained in the div. 

The fourth map, with polygons instead of pins, does not move the map to contain the pop-up. You can get something like this if you happen to click in the wrong place:

<img width="644" alt="Screenshot 2025-01-07 at 10 05 25" src="https://github.com/user-attachments/assets/c0cb32fe-2e9c-4be0-8c9f-3bfc0e11c8f2" />

**Comment by jimsafley** [comment]
Oh, yeah, there's nothing I can do about that. The popup opens wherever the user clicks the polygon. Leaflet has no way to "correct" the placement of the popup after the map pans/zooms to contain the features.

**Comment by allanaaa** [comment]
Aw, but it works so well on the map above that! 

Okay, I think this is good to go. I'll file theme issues as needed. 

I think we have a substantial chunk of things to document - once you fold all these branches into develop, I'll also do some last testing to make sure everything is placing nicely with each other.

**Comment by jimsafley** [comment]
Great! I'll create a documentation issue.
