### ISSUE TITLE
Front admin page has error

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/Mapping#21]
Pulled latest core and Mapping. Mapping is the only active module. Did install-deps.

Throws this on the main admin page (`/admin`)

```
There was an error.

PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'm0_.bounds' in 'field list' in /var/www/omekas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104
Stack trace:
#0 /var/www/omekas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(104): PDO->query('SELECT m0_.id A...')
#1 /var/www/omekas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(833): Doctrine\DBAL\Driver\PDOConnection->query('SELECT m0_.id A...')
#2 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(50): Doctrine\DBAL\Connection->executeQuery('SELECT m0_.id A...', Array, Array, NULL)
#3 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(321): Doctrine\ORM\Query\Exec\SingleSelectExecutor->execute(Object(Doctrine\DBAL\Connection), Array, Array)
#4 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(969): Doctrine\ORM\Query->_doExecute()
#5 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(924): Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache(NULL, 1)
#6 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(727): Doctrine\ORM\AbstractQuery->execute(NULL, 1)
#7 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Pagination/Paginator.php(171): Doctrine\ORM\AbstractQuery->getResult(1)
#8 /var/www/omekas/application/src/Api/Adapter/AbstractEntityAdapter.php(225): Doctrine\ORM\Tools\Pagination\Paginator->getIterator()
#9 /var/www/omekas/application/src/Api/Manager.php(209): Omeka\Api\Adapter\AbstractEntityAdapter->search(Object(Omeka\Api\Request))
#10 /var/www/omekas/application/src/Api/Manager.php(58): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#11 /var/www/omekas/modules/Mapping/Module.php(215): Omeka\Api\Manager->search('mappings', Array)
#12 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Mapping\Module->cacheItemMappingData(Object(Omeka\Event\Event))
#13 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(143): Zend\EventManager\EventManager->triggerListeners(Object(Omeka\Event\Event))
#14 /var/www/omekas/application/src/Api/Manager.php(265): Zend\EventManager\EventManager->triggerEvent(Object(Omeka\Event\Event))
#15 /var/www/omekas/application/src/Api/Manager.php(58): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#16 /var/www/omekas/application/src/Mvc/Controller/Plugin/Api.php(49): Omeka\Api\Manager->search('items', Array)
#17 /var/www/omekas/application/src/Controller/Admin/IndexController.php(12): Omeka\Mvc\Controller\Plugin\Api->search('items', Array)
#18 /var/www/omekas/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): Omeka\Controller\Admin\IndexController->browseAction()
#19 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#20 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(151): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#21 /var/www/omekas/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(105): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#22 /var/www/omekas/vendor/zendframework/zend-mvc/src/DispatchListener.php(119): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#23 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#24 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(151): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#25 /var/www/omekas/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#26 /var/www/omekas/index.php(17): Zend\Mvc\Application->run()
#27 {main}

Next Doctrine\DBAL\Driver\PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'm0_.bounds' in 'field list' in /var/www/omekas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106
Stack trace:
#0 /var/www/omekas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(833): Doctrine\DBAL\Driver\PDOConnection->query('SELECT m0_.id A...')
#1 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(50): Doctrine\DBAL\Connection->executeQuery('SELECT m0_.id A...', Array, Array, NULL)
#2 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(321): Doctrine\ORM\Query\Exec\SingleSelectExecutor->execute(Object(Doctrine\DBAL\Connection), Array, Array)
#3 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(969): Doctrine\ORM\Query->_doExecute()
#4 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(924): Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache(NULL, 1)
#5 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(727): Doctrine\ORM\AbstractQuery->execute(NULL, 1)
#6 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Pagination/Paginator.php(171): Doctrine\ORM\AbstractQuery->getResult(1)
#7 /var/www/omekas/application/src/Api/Adapter/AbstractEntityAdapter.php(225): Doctrine\ORM\Tools\Pagination\Paginator->getIterator()
#8 /var/www/omekas/application/src/Api/Manager.php(209): Omeka\Api\Adapter\AbstractEntityAdapter->search(Object(Omeka\Api\Request))
#9 /var/www/omekas/application/src/Api/Manager.php(58): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#10 /var/www/omekas/modules/Mapping/Module.php(215): Omeka\Api\Manager->search('mappings', Array)
#11 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Mapping\Module->cacheItemMappingData(Object(Omeka\Event\Event))
#12 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(143): Zend\EventManager\EventManager->triggerListeners(Object(Omeka\Event\Event))
#13 /var/www/omekas/application/src/Api/Manager.php(265): Zend\EventManager\EventManager->triggerEvent(Object(Omeka\Event\Event))
#14 /var/www/omekas/application/src/Api/Manager.php(58): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#15 /var/www/omekas/application/src/Mvc/Controller/Plugin/Api.php(49): Omeka\Api\Manager->search('items', Array)
#16 /var/www/omekas/application/src/Controller/Admin/IndexController.php(12): Omeka\Mvc\Controller\Plugin\Api->search('items', Array)
#17 /var/www/omekas/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): Omeka\Controller\Admin\IndexController->browseAction()
#18 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#19 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(151): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#20 /var/www/omekas/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(105): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#21 /var/www/omekas/vendor/zendframework/zend-mvc/src/DispatchListener.php(119): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#22 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#23 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(151): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#24 /var/www/omekas/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#25 /var/www/omekas/index.php(17): Zend\Mvc\Application->run()
#26 {main}

Next Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT m0_.id AS id_0, m0_.bounds AS bounds_1, m0_.item_id AS item_id_2 FROM mapping m0_ GROUP BY m0_.id ORDER BY m0_.id ASC':

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'm0_.bounds' in 'field list' in /var/www/omekas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71
Stack trace:
#0 /var/www/omekas/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /var/www/omekas/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(836): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT m0_.id A...', Array)
#2 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(50): Doctrine\DBAL\Connection->executeQuery('SELECT m0_.id A...', Array, Array, NULL)
#3 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(321): Doctrine\ORM\Query\Exec\SingleSelectExecutor->execute(Object(Doctrine\DBAL\Connection), Array, Array)
#4 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(969): Doctrine\ORM\Query->_doExecute()
#5 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(924): Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache(NULL, 1)
#6 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(727): Doctrine\ORM\AbstractQuery->execute(NULL, 1)
#7 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Pagination/Paginator.php(171): Doctrine\ORM\AbstractQuery->getResult(1)
#8 /var/www/omekas/application/src/Api/Adapter/AbstractEntityAdapter.php(225): Doctrine\ORM\Tools\Pagination\Paginator->getIterator()
#9 /var/www/omekas/application/src/Api/Manager.php(209): Omeka\Api\Adapter\AbstractEntityAdapter->search(Object(Omeka\Api\Request))
#10 /var/www/omekas/application/src/Api/Manager.php(58): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#11 /var/www/omekas/modules/Mapping/Module.php(215): Omeka\Api\Manager->search('mappings', Array)
#12 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Mapping\Module->cacheItemMappingData(Object(Omeka\Event\Event))
#13 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(143): Zend\EventManager\EventManager->triggerListeners(Object(Omeka\Event\Event))
#14 /var/www/omekas/application/src/Api/Manager.php(265): Zend\EventManager\EventManager->triggerEvent(Object(Omeka\Event\Event))
#15 /var/www/omekas/application/src/Api/Manager.php(58): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#16 /var/www/omekas/application/src/Mvc/Controller/Plugin/Api.php(49): Omeka\Api\Manager->search('items', Array)
#17 /var/www/omekas/application/src/Controller/Admin/IndexController.php(12): Omeka\Mvc\Controller\Plugin\Api->search('items', Array)
#18 /var/www/omekas/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): Omeka\Controller\Admin\IndexController->browseAction()
#19 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#20 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(151): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#21 /var/www/omekas/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(105): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#22 /var/www/omekas/vendor/zendframework/zend-mvc/src/DispatchListener.php(119): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#23 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#24 /var/www/omekas/vendor/zendframework/zend-eventmanager/src/EventManager.php(151): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#25 /var/www/omekas/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#26 /var/www/omekas/index.php(17): Zend\Mvc\Application->run()
#27 {main}



```

**Comment by jimsafley** [comment]
Try reinstalling if you haven't already.

**Comment by patrickmj** [comment]
Thanks. That looks like it did it.
