### ISSUE TITLE
Related to Issue #36

### ISSUE THREAD

**Issue by kernsb** [omeka-s-modules/Mapping#37]
The resolution for Issue #36 mostly resolved the issue with non-Admins getting a "Forbidden" error when adding an item with Mapping data. However, I have discovered that the non-Admin users still receive "Forbidden" if they set a default view for the map when adding Mapping data.

**Comment by kernsb** [comment]
I am not seeing this as resolved with the a03e522 pull. I am still able to create and item with a map, but under an "Author" account, I am unable to use the "Set the current view as the default view" button, I still receive "Forbidden" upon creation.

**Comment by patrickmj** [comment]
Thanks. It works okay on my installation, both as Editor and Author, so there's something more weird happening. If you haven't already, in the `.htaccess` could you change the application environment to `SetEnv APPLICATION_ENV "development"` to give more detailed error messages, and post of the entire error message here?

Also, what version of Omeka S are you currently on?

**Comment by kernsb** [comment]
Sure thing, we're running on 1.0.0-rc.1. Here is the full error:
```
Omeka\Api\Exception\PermissionDeniedException: Permission denied for the current user to create the Mapping\Entity\Mapping resource. in /usr/local/omeka/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php:588
Stack trace:
#0 /usr/local/omeka/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(533): Omeka\Api\Adapter\AbstractEntityAdapter->authorize(Object(Mapping\Entity\Mapping), 'create')
#1 /usr/local/omeka/omeka-s/modules/Mapping/Module.php(307): Omeka\Api\Adapter\AbstractEntityAdapter->hydrateEntity(Object(Omeka\Api\Request), Object(Mapping\Entity\Mapping), Object(Omeka\Stdlib\ErrorStore))
#2 /usr/local/omeka/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Mapping\Module->handleMapping(Object(Zend\EventManager\Event))
#3 /usr/local/omeka/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(171): Zend\EventManager\EventManager->triggerListeners(Object(Zend\EventManager\Event))
#4 /usr/local/omeka/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(560): Zend\EventManager\EventManager->triggerEvent(Object(Zend\EventManager\Event))
#5 /usr/local/omeka/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(267): Omeka\Api\Adapter\AbstractEntityAdapter->hydrateEntity(Object(Omeka\Api\Request), Object(Omeka\Entity\Item), Object(Omeka\Stdlib\ErrorStore))
#6 /usr/local/omeka/omeka-s/application/src/Api/Manager.php(224): Omeka\Api\Adapter\AbstractEntityAdapter->create(Object(Omeka\Api\Request))
#7 /usr/local/omeka/omeka-s/application/src/Api/Manager.php(78): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#8 /usr/local/omeka/omeka-s/application/src/Mvc/Controller/Plugin/Api.php(99): Omeka\Api\Manager->create('items', Array, Array, Array)
#9 /usr/local/omeka/omeka-s/application/src/Controller/Admin/ItemController.php(212): Omeka\Mvc\Controller\Plugin\Api->create('items', Array, Array)
#10 /usr/local/omeka/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): Omeka\Controller\Admin\ItemController->addAction()
#11 /usr/local/omeka/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#12 /usr/local/omeka/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#13 /usr/local/omeka/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(106): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#14 /usr/local/omeka/omeka-s/vendor/zendframework/zend-mvc/src/DispatchListener.php(138): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#15 /usr/local/omeka/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#16 /usr/local/omeka/omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#17 /usr/local/omeka/omeka-s/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#18 /usr/local/omeka/omeka-s/index.php(21): Zend\Mvc\Application->run()
#19 {main}
```

**Comment by patrickmj** [comment]
Thanks. Sadly, still weird. I was hoping that permissions problem would be different from the `Mapping\Entity\Mapping resource`, but https://github.com/omeka-s-modules/Mapping/blob/master/Module.php#L34 and following seem like they should fix it. My change to that was got it working for me, at least.

My fallback is often to check if another module is affecting things, and deactivating others makes it work.

At least on my own laptop, sometimes I've seen weird situations where restarting the server fixes things -- some kind of weird caching that I haven't tracked down. Don't know if that's a possibility, but if it is, it might give an interesting data point.

**Comment by kernsb** [comment]
My apologies, it looks like my pull didn't take. I tried again to make sure, and sure enough after that time things are working! Thanks for your time, and sorry again for the mistake!

**Comment by patrickmj** [comment]
No problem! There are gremlins everywhere.
