### ISSUE TITLE
map-browse throws error when public geo-located item has a "private" media

### ISSUE THREAD

**Issue by giocomai** [omeka-s-modules/Mapping#80]
If any of the items available to a site has visibility set to "public", but its related media has visibility set to "private", the "/map-browse/" page of the site just throws an error with no further details. 

I understand this is an unusual situation, but I still feel this is a bug, as changing the visibility setting of an item basically breaks the website. 

The issue appears only to website visitors, while logged-in users who have access to the media do not experience any issue. 

This is the full error message that appears with `development` mode enabled with Omeka S 3.0.1 and the latest version of the module, but I confirm the same issue on the latest version of the module available for Omeka S 2. 

```
Omeka S ha riscontrato un errore

Doctrine\ORM\EntityNotFoundException
Entity of type 'Omeka\Entity\Media' for IDs id(12345) was not found

Dettagli:

Doctrine\ORM\EntityNotFoundException: Entity of type 'Omeka\Entity\Media' for IDs id(6636) was not found in /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/EntityNotFoundException.php:47
Stack trace:
#0 /var/www/html/vendor/doctrine/orm/lib/Doctrine/ORM/Proxy/ProxyFactory.php(166): Doctrine\ORM\EntityNotFoundException::fromClassNameAndIdentifier('Omeka\\Entity\\Me...', Array)
#1 /var/www/html/application/data/doctrine-proxies/__CG__OmekaEntityMedia.php(354): Doctrine\ORM\Proxy\ProxyFactory->Doctrine\ORM\Proxy\{closure}(Object(DoctrineProxies\__CG__\Omeka\Entity\Media), 'hasThumbnails', Array)
#2 /var/www/html/application/data/doctrine-proxies/__CG__OmekaEntityMedia.php(354): Closure->__invoke(Object(DoctrineProxies\__CG__\Omeka\Entity\Media), 'hasThumbnails', Array)
#3 /var/www/html/application/src/Api/Representation/MediaRepresentation.php(238): DoctrineProxies\__CG__\Omeka\Entity\Media->hasThumbnails()
#4 /var/www/html/application/src/Api/Representation/MediaRepresentation.php(67): Omeka\Api\Representation\MediaRepresentation->hasThumbnails()
#5 /var/www/html/volume/modules/Mapping/view/mapping/site/index/browse.phtml(32): Omeka\Api\Representation\MediaRepresentation->thumbnailUrl('medium')
#6 /var/www/html/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(505): include('/var/www/html/v...')
#7 /var/www/html/vendor/laminas/laminas-view/src/View.php(206): Laminas\View\Renderer\PhpRenderer->render(NULL)
#8 /var/www/html/vendor/laminas/laminas-view/src/View.php(235): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#9 /var/www/html/vendor/laminas/laminas-view/src/View.php(199): Laminas\View\View->renderChildren(Object(Laminas\View\Model\ViewModel))
#10 /var/www/html/vendor/laminas/laminas-mvc/src/View/Http/DefaultRenderingStrategy.php(104): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#11 /var/www/html/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Laminas\Mvc\MvcEvent))
#12 /var/www/html/vendor/laminas/laminas-eventmanager/src/EventManager.php(170): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent))
#13 /var/www/html/vendor/laminas/laminas-mvc/src/Application.php(366): Laminas\EventManager\EventManager->triggerEvent(Object(Laminas\Mvc\MvcEvent))
#14 /var/www/html/vendor/laminas/laminas-mvc/src/Application.php(347): Laminas\Mvc\Application->completeRequest(Object(Laminas\Mvc\MvcEvent))
#15 /var/www/html/index.php(21): Laminas\Mvc\Application->run()
#16 {main}
```

**Comment by jimsafley** [comment]
I cannot reproduce this. I have a public item with a private media and I can view the map browse page while logged out. I'll continue looking into this.

**Comment by jimsafley** [comment]
Thanks for pointing this out. The fix should be in the next release.

**Comment by giocomai** [comment]
Looks great! Thanks for taking the time to investigate and fix this!
